"""initial migration

Revision ID: d579e78424be
Revises: 
Create Date: 2026-03-25 16:54:32.158465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd579e78424be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id_kategori', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_kategori', name=op.f('pk_categories'))
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('telegram_number', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id_user', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('websites',
    sa.Column('id_web', sa.Integer(), nullable=False),
    sa.Column('nama_web', sa.String(length=100), nullable=True),
    sa.Column('url_web', sa.String(length=200), nullable=True),
    sa.Column('slug_web', sa.String(length=200), nullable=True),
    sa.Column('deskripsi_web', sa.String(length=256), nullable=True),
    sa.Column('kategori_web', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kategori_web'], ['categories.id_kategori'], name=op.f('fk_websites_kategori_web_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_web', name=op.f('pk_websites'))
    )
    op.create_table('pages',
    sa.Column('id_page', sa.Integer(), nullable=False),
    sa.Column('id_web', sa.Integer(), nullable=False),
    sa.Column('halaman_web', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_web'], ['websites.id_web'], name=op.f('fk_pages_id_web_websites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_page', name=op.f('pk_pages'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages')
    op.drop_table('websites')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
