"""initial

Revision ID: f7469274d515
Revises: 
Create Date: 2025-09-11 11:24:36.871227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7469274d515'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.alter_column('halaman_web',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('websites_id_web'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_pages_id_web_websites'), 'websites', ['id_web'], ['id_web'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('username'))
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.alter_column('nama_web',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('link_web',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.alter_column('slug_web',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.alter_column('slug_web',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('link_web',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('nama_web',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pages_id_web_websites'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('websites_id_web'), 'websites', ['id_web'], ['id_web'], onupdate='CASCADE')
        batch_op.alter_column('halaman_web',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50),
               nullable=False)

    # ### end Alembic commands ###
